Bitbox-Connect/Bitbox

client/package-lock.json
client/package.json
client/postcss.config.js
client/src/App.jsx
client/src/atom/Atom.js
client/src/component/Home.jsx
client/src/component/Login.jsx
client/src/component/MyProfile.jsx
client/src/component/Navbar.jsx
client/src/component/Signup.jsx
client/src/component/css/Auth.css
client/src/index.css
client/tailwind.config.js
server/db.js
server/package-lock.json
server/package.json

issue:#2
- created Login and SignUp page. 
- removed the navigation bar form the login and signup page to give them more impactful visuals.

redesign login/sign

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/component/Login.jsx
client/src/component/forgotpass.jsx
server/package-lock.json
server/package.json
server/routes/auth.js

i have added forgot page review  the changes and accept the pull request

added forgot page

---

client/src/component/Login.jsx
client/src/component/Navbar.jsx
client/src/component/css/Auth.css
client/src/component/css/Navbar.css

review the changes and accept the pull request

Bitbox login and navbar ui changes

---

client/index.html
client/src/App.css
client/src/App.jsx
client/src/component/Home.jsx
client/src/component/HomePage/Card.jsx
client/src/component/css/Home.css
client/tailwind.config.js

Fix for #12 
- Added responsiveness to the card section
- Created a separate component for Cards
- Changed from static to dynamic update for cards
- Improved the legibility of the text for the description
- added the google font in the css file so that it can be accessible to all
- To use a better typeface
- Revamp the whole landing page to one interactive one

Fix for #12 : Card-Improvement

---

CONTRIBUTING.md

This PR introduces a CONTRIBUTORS.md file that outlines the contribution guidelines for the BitBox project. It includes steps for setting up the project, coding standards, and how to raise issues or submit pull requests. This document aims to streamline the onboarding process for new contributors, ensuring a clear understanding of how to contribute effectively to the project. Thank you for considering this addition!

Add CONTRIBUTORS.md file to provide guidelines for project contributions

---

client/src/component/Discussion.jsx
client/src/component/InputModal.jsx

Solve null user issue and add Modal..
@Anuj3553 please add hactoberfest label to it , and one more request if there is any work related to **backend** i would like on work on it.

Null user in discussion page error resolve

---

client/src/App.jsx
client/src/component/Verify.jsx
client/src/component/forgotpass.jsx
client/src/index.css
server/.env.sample
server/.gitignore
server/Controllers/auth.js
server/Controllers/profiles.js
server/Models/User.js
server/package-lock.json
server/package.json
server/routes/auth.js
server/routes/profile.js

#25 
After the signup process, you need to provide your email for verification. Once you click the verification link, the user is redirected to the home page. After confirmation, the user can log in or log out.
@Anuj3553 , you can merge the PR. If there are any other tasks for me, I would love to work on them.

Email verification done

---

README.md

Bitbox Readme Over Content problem

---

.github/workflows/greetings.yml

This PR adds a new GitHub Actions workflow that automatically greets first-time contributors when they open issues or pull requests. This helps create a welcoming environment for new contributors and acknowledges their efforts.
Resolved Issue #51 
Changes:
- Added .github/workflows/greetings.yml file
please review and merge,
Thank You

Successfully added Github bot to respond Issues and PR

---

client/package-lock.json
client/package.json
client/src/component/Login.jsx
client/src/component/Signup.jsx
client/src/component/css/Login.css
client/src/validations/validation.js
server/package-lock.json
server/package.json

Hello
I have added the input validations for login and signup pages
pls check it

added input validations

---

client/src/component/Login.jsx
server/Controllers/auth.js
server/index.js
server/routes/auth.js

added an modal on the frontend and an api on the backend which lets user use the functionality of forgot password 
when the user fills email on the modal and press submit 
image2:
an email is sent with the url of forgot password page by which user can visit the page and reset the password 
advantage:
only the authenticated user will be able to reset the password as the email will go only to that user 
email will go like this:
please add gssoc-ext and level3 label before merge

added email reset functionality

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/index.css
client/src/main.jsx

custom cursor added

---

client/src/App.jsx

Added missing import in header

---

client/package-lock.json
client/src/App.jsx
client/src/component/Home.jsx
client/src/component/css/Home.css
server/db.js

Changed styling and alignment hovering color combination fixed.

Style of what we work on changed and corrected

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md

i have added issue template and pr templates

Issue template added #105

---

README.md

Improved some code redability and efficiency.

Needed to change some code related to features

---

server/package-lock.json
server/package.json
server/routes/auth.js

**Added rate llimiter to the login api**
**Issue No.:**
Close #111
---
ihave tested using postman:
login with wrong password 5 times:
on the 6 th time the api will not  process the request for 5 minutes
it will:
prevent bots attack
reduce the load on the login api
---
**please add gssoc-ext and level2 before merge**

added rate limiter to the login api issue #111

---

server/.env_sample

**Title:** Addition of .env_sample file in server
**Issue No.:** #113 
Close #113 
---
updated server folder 
---
**Additional context (Mandatory):** I have added all the necessary env variable to .env_sample file if any further changes required please let me know.

added env_sample file

---

client/src/component/Login.jsx
client/src/component/Signup.jsx
client/src/main.jsx

Fixes #109 
**Title:**
Notification during login and signup.
**Issue No.:**
Close #109 
After completion of signup Toast.success will show successfull message in case of error it will show error.
After completion of Login Toast.success will show successfull message in case of error it will show error.
---
Yes
GSSOC-EXT, HACKTOBERFEST

BUG: Notification Added during login and signup

---

client/src/component/Login.jsx
client/src/component/Signup.jsx
client/src/main.jsx
server/Controllers/auth.js

**Title:**
Edit the default image of profile slider replace image to first letter of user name.
**Issue No.:**
Close #108 
---
When user created then user model will have default image of current username.

Bug/Edit Default Image

---

client/src/component/Footer.jsx
client/src/component/Login.jsx
client/src/component/Signup.jsx
client/src/main.jsx
server/Controllers/auth.js

**Title:**
Replace old twitter icon to X-Twitter icon.
**Issue No.:**
Close #107 
---
---

BUG Update Twitter X-Icon

---

client/src/App.jsx
client/src/component/Discussion.jsx
client/src/component/Login.jsx
server/Controllers/auth.js
server/Controllers/profiles.js
server/db.js
server/index.js
server/routes/auth.js
server/routes/projects.js

**Title: Fixed the login and signup api**
**Issue No.: #86**
Close #86
---
---

Fixed the login and signup route

---

client/src/component/css/Navbar.css

#127 
**Title:** Improve the UI of the navbar.
**Issue No.:**  #127
---
before:
after :
---
- [x ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [x ] I have gone through the `contributing.md` file before contributing.
- [ x] I'm a GSSOC-EXT contributor
- [ x] I'm a HACKTOBERFEST contributor

Improve the UI of the navbar.

---

client/src/App.jsx
client/src/component/ProgressBar/ProgressBar.css
client/src/component/ProgressBar/ProgressBar.jsx

**Title:** ProgressBar Added
**Issue No.:** #114 
Close #114 of Level 2
---
Uploading bandicam 2024-10-17 03-19-40-532.mp4…
---

ProgressBar Added | Issue #114

---

client/package-lock.json
client/src/component/About.jsx
client/src/component/css/About.css
client/src/component/css/Navbar.css

**Title: Enhancing the Ui of FAQ and About Us page .**
**Issue No.: #136**
Close #<136>
---
CHANGES MADE :
---
- [X ] I have mentioned the issue number in my Pull Request.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have gone through the `contributing.md` file before contributing.
So I have done changes based on the theme of the website and did went out of  my way to make changes that would be unnecessary.
Hope you will like it .
- [X ] I'm a GSSOC-EXT contributor
- [X ] I'm a HACKTOBERFEST contributor

  #136 -- Enhancing UI .

---

client/src/component/Footers/Contactus.jsx

**Title:** React Toast, and Form Validation Addition | Issue #135
**Issue No.:** #135 
Close #135 
---
https://github.com/user-attachments/assets/8fd14a51-cee7-40cc-9268-91829d17e4bb
---

React Toast, and Form Validation Addition | Issue #135

---

client/src/component/Footer.jsx
client/src/component/css/Footer.css

**Title: Improve the Footer Design on the Main Page**
**Issue No.:157**
Fixes #157
---
As now it is working fine for phone and tablets and also the UI of footer improved for better user experience for
both Dark Mode and Light Mode.
**LIGHT MODE**
**DARK MODE**
**MOBILE RESPONSIVE**
---
To enhance the mobile responsiveness and user interaction of your footer, adopt a mobile-first design using CSS Flexbox or Grid to ensure flexible layouts that stack vertically on smaller screens. Incorporate interactive elements like subtle hover effects on links and animated social media icons to engage users. Ensure accessible navigation by clearly labeling all links and using aria-label for icons. Integrate feedback mechanisms, such as a modal for user suggestions and …

Added [Responsive-Footer]

---

client/src/component/Navbar.jsx
client/src/index.css

**Title:** Added Custome Scrolbar 
**Issue No.:** #145 
Close #145 
---
https://github.com/user-attachments/assets/b8a30e47-1c4a-4071-a6dd-5963f28d7363
---

Added Custome Scrolbar | Issue #145

---

client/src/component/Navbar.jsx

**Title:** Fix Navbar 
**Issue No.:** #140 
Close #140 
---
Before : 
https://github.com/user-attachments/assets/3cf8b273-9b04-45fb-b501-15f08a24bdec
After :
https://github.com/user-attachments/assets/ebf0bab3-5284-4983-ba0f-b0e5076ea840
---

Fix Navbar | Issue #140

---

client/src/App.jsx
client/src/component/NotFound.jsx

Fixes #162  Added Custom Error Page
Enhance the ui design of custom 404 error page of this website .. After Successfully Merging closes the issue #162 
Before
After Fixing 
---
- [ X] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [X ] I have gone through the `contributing.md` file before contributing.
- [ X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

Added Custom Error Page

---

client/src/component/Login.jsx
client/src/component/Signup.jsx
client/src/component/css/Login.css
client/src/component/css/Signup.css

Inconsistent Design and Usability Issues in Login and Signup UI and #124
Inconsistent Design and Usability Issues in Login and Signup UI
#124 
Close #124 
---
both dark and light mode
---

Resolve the design issues of login & signup page

---

client/src/component/Home.css
client/src/component/Home.jsx
server/package-lock.json

#fixe the alignment of text and #150 
**Title:**
make word section responsive and fixed the alignment 
**Issue No.:#150
Close #<150>
https://github.com/user-attachments/assets/28db0436-9348-4ac4-bee5-27e123899b64
---

make word section responsive

---

client/src/component/Home.jsx

**Title:**
**Issue No.:**
Close #167 
---
https://github.com/user-attachments/assets/244699b5-a8a9-43d6-8e29-e56311b4106b
---

Added scroll animations to hero and bitbox community section.

---

client/src/component/css/Footer.css

In this PR, I have enhanced the hover effects for the links and social media icons in the footer section. The changes include:
Added a smooth transform: scale(1.05) effect to all links within the footer, making them slightly larger when hovered over to improve user interaction and visual appeal.
Adjusted the social media icons with transform: scale(1.1) on hover, providing a more dynamic and engaging user experience.
Included transition properties for both transform and color to ensure smooth transitions between states.
Updated the dark mode styles to maintain readability, adjusting the hover colors to fit better with the dark theme.
These changes create a more appealing and user-friendly interface for the footer section, providing a consistent and polished look.
I'm a GSSOC-EXT …

I have done changes in footer section to improve its appearance.

---

README.md

**Title:**
- Building up a Contact Channel in Readme.md
**Issue No.:**
- Issue #186 
Close #186 
---
https://github.com/user-attachments/assets/19b522de-8e1a-4235-a235-c6433cd8255e
---

Building up a Contact Channel in Readme.md 

---

client/package-lock.json
client/src/App.jsx
client/src/component/ForgotPassword.jsx
client/src/component/Login.jsx

**Title:** 
Integrate Password Recovery Feature
**Issue No.:**
Close #189 
---
https://github.com/user-attachments/assets/56322c3f-6e2f-431d-a825-ae5ed8516f5a
---
This PR implements the password recovery feature, enhancing user experience by allowing password reset functionality. It resolves the issue of users being unable to recover their accounts if they forget their passwords, contributing to better usability and security for the application.

Integrate Password Recovery Feature #189

---

client/index.html

**Title:** Added multi Language support system
**Issue No.:** 151
Close #151 
---
https://github.com/user-attachments/assets/af5a6819-5fc7-4450-ab31-8473221056eb
---

added multilanguage support for enhanced user experience #151

---

client/package-lock.json
client/src/component/EditProfile.jsx
client/src/component/Login.jsx
client/src/css/EditProfile.css

made the edit profile page responsive
issue number #230 
photo 2:
please add gssoc-ext and level2 before merge @Anuj3553

responsive edit profile page

---

README.md

**Title:** Add Stargazers and Forkers Profiles to README.md 
**Issue No.:** #255 
Close #255
---
---

Added Stargazers and Forkers Profiles to README.md 

---

README.md

**Title:**Add License Section to README.md✨
**Issue No.:** #280 
Close #280
---
---

Add License Section to README.md✨

---

client/src/App.jsx
client/src/component/Contributors.jsx
client/src/component/Navbar.jsx

**Title:** Adding a new page to display all contributors
**Issue No.:** 350
Close #350
---
---
I add a usfull page Contribution that motivated all contributors.

Add Contributors Page and Display all contributors in a single page

---

client/src/component/Faq.jsx
client/src/component/Navbar.jsx
client/src/css/Navbar.css

**Title:** Navbar fixed in responsive and full mode 
**Issue No.:**
Close #328 done
---
https://github.com/user-attachments/assets/6b22ca4f-4c5a-48b5-ad36-7c7ef5942784
- [ X] I have mentioned the issue number in my Pull Request.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have created a helpful and easy-to-understand `README.md` if it's a new page/tech stack.
- [X ] I have gone through the `contributing.md` file before contributing.
- [X ] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

navbar fixed in both mode : #328 done

---

client/src/component/Home.jsx

This PR addresses the issue where the content on the homepage is hidden behind the navbar. The changes ensure that the homepage content is properly aligned and fully visible, improving the overall user experience.
**Issue No.:**
Close #376 

Fixed Home Page alignment with respect to navbar

---

client/src/component/Footers/Contactus.jsx

**Title:** Add Validation to contact us Message Field
**Issue No.:**
Close #324 
---
---

Add Validation to contact us Message Field

---

client/index.html
client/src/component/Footer.jsx
client/src/component/Footers/VisitorCount.jsx
client/src/css/Footer.css

I've refined the styling and added decorative elements to enhance the design's appeal. The updates improve both the aesthetic and user experience. Please review the changes, and if everything looks good, go ahead with the merge.

STYLING IMPROVED
